### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by devenv** [arjunmehta/multiview#3]
Error: Cannot find module './build/Debug/buffertools.node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/multiview/node_modules/buffertools/buffertools.js:26:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by devenv** [comment]
[Error: Module version mismatch. Expected 46, got 48.]

**Comment by arjunmehta** [comment]
@devenv Strange. Can you post which version of node you're using and which version of npm you're using?

Thanks!

**Comment by devenv** [comment]
Sure
npm -v
2.14.20
node -v
v4.4.1

**Comment by arjunmehta** [comment]
Fixed in v2.4.0
